### ISSUE TITLE
Problem with tuple(pro_co.index) object

### ISSUE THREAD

**Issue by lucaNicoli88** [tum-ewk/ficus#1]
Hi, 
I am trying to execute your _example.xls_ file using ficus project.
Executing the code, I have the following issue:
_ValueError: Length of names must match number of levels in MultiIndex._

The problem is raise from **`del_processes()`** method in ficus.py file.
The following part of code cause the issue:
`pro_co.index=pd.MultiIndex.from_tuples(tuple(pro_co.index),names=process_commodity.index.names[0:1]+['Num'] + process_commodity.index.names[1:3])`

The following object is `tuple(pro_co.index)`:
![image](https://user-images.githubusercontent.com/36009099/35639222-d528371c-06b9-11e8-9569-29a9502d80b5.png)

The first element of this tuple (`tuple(pro_co.index)[0]`) is a tuple with only one element and a final comma.  `Out[18]: (('chp', 1, 'gas', 'In'),)` This cause the ValueError that i am just reporting.

Can you help me?

Best.

**Comment by yabata** [comment]
Should work now. It was a problem with the new pandas version.
