### ISSUE TITLE
retrun pro_co

### ISSUE THREAD

**Issue by MGindi** [tum-ewk/ficus#2]
Hi

I have a problem running any of the example files.

I tried running it via python and directly from the excel sheet file. In both attempts I reach the same point as shown in the attached image.
![frozen_or_not_excel](https://user-images.githubusercontent.com/1587157/75021166-a2babd80-549c-11ea-90b0-010cac200b77.png)

**Comment by yabata** [comment]
Seems like there are some changes in the new pandas version (>=1.0). Try using pandas=0.23.4 that works fine for me. (pip install pandas==0.23.4)

**Comment by MGindi** [comment]
I tried installing pandas 0.23.4, python 2.7. and on Ubuntu, just to be sure that the problem is independent of the python version and OS yet the same issue remains.

I assume I am missing a step or two in the middle that probably leads to this issue since I have another colleague tried to run the same example file on his PC and he has the same issue.

Here is how I did it:

1) installed Anconda 3.7 on Windows 10.
2) installed pyomo via "pip install pyomo"
3) modified runficus.py file -> changed opt= 'cplex' to opt='cbc' and neos = True
as described in the documentation website
prob = ficus.run_ficus(input_file, opt = 'cbc', neos = True)
4) import runficus

I get a screen similar to the one I posted above. I left it for hours but it didn't show any progress further than this point.

This is the messages I get when I hit ctrl+D
![Screenshot from 2020-02-21 19-39-52](https://user-images.githubusercontent.com/1587157/75058659-17651a80-54e4-11ea-94af-f7710fced2cf.png)

**Comment by MGindi** [comment]
Hi again,

I downloaded ficus from this link:

https://github.com/yabata/ficus/blob/master/ficus.py

after deleting lines 1358, and 1359 from the script, the same as the one available in this link:

https://github.com/tum-ewk/ficus/blob/master/ficus.py

 it now works fine.

Thank you for your support
